sudo: required
language: node_js

node_js:
  - 10

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE url_shortener;'

script:
  - npm test
  - cd ./client-js && npm test && cd ..

on:
  branch: master
