sudo: required
language: node_js

node_js:
  - 10

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE url_shortener;'
  - cd ./client-js && npm install && cd ..

script:
  - npm test
  - cd ./client-js && npm test && cd ..

deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: $HEROKU_API_KEY
  app: url-shortener-10
