sudo: required
language: node_js

node_js:
  - 10

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE url_shortener;'
  - cd ./client-js && npm install && cd ..

script:
  - npm run build
  - npm test
