version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y mysql-server
      - sudo systemctl start mysql
      - sudo mysql -e 'CREATE DATABASE url_shortener;'
  pre_build:
    commands:
      - npm install
      - cd ./client-js && npm install && cd ..
      - cd ./sass && npm install && cd ..
  build:
    commands:
      - npm run build
      - npm test

artifacts:
  files:
    - public/*
    - scripts/*
    - server/**/*
    - appspec.yml
    - package-lock.json
    - package.json
